export PS1='\[\033[0;36m\]`hostname`:\w>\[\033[0m\] '
#export PS1="\e[36m\`hostname\`:\${PWD}>\e[0m "
#export  PS1="\`hostname\`:\${PWD}>"
#export PS1='\u:\w\$ '
alias ll="ls -al --color"
alias grep="grep --color"
